language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - sys-img-armeabi-v7a-android-28
    - extra-android-m2repository

script: ./gradlew build assembleRelease

deploy:
  - provider: releases
    api_key: 6322bb1898cc3e83ca6902b9f08e78cd922403a5
    file: app/build/outputs/apk/app-release.apk
    on:
      repo: SlipkHunter/SocksHttp
      tags: true